[package]
name = "neuralnet"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.13.3"
dotenvy = "0.15.7"
env_logger = "0.11.3"
itertools = "0.12.1"
log = { version = "0.4.21", features = ["std"] }
nalgebra = "0.32.5"
rand = "0.8.5"
